#--
install:
  zip: install.zip
  files:   wiphoto/CSS wiphoto/images wiphoto/index.html wiphoto/js
  exclude: \*~ \*/albums.js \*/photos.js \*/.DS_Store \*/\#\*

albums:
   names: SELECT primaryKey, Name, Parent,ClassName FROM SqAlbum WHERE primaryKey < 999000
#ClassName= 'Album'
# AND albumGroup = 8192
#
# Find folders togetherwith albums in folders
# select primaryKey,parent,siblingOrder,repAlbumKeyForLoading from SqAlbum
# primaryKey is from names: SQL
   photos: "SELECT sqPhotoInfo FROM AlbumsPhotosJoin where sqAlbum = #{primaryKey} ORDER BY photosOrder"

   tree:
     top: "SELECT PrimaryKey FROM sqAlbum WHERE Parent = 0 AND PrimaryKey < 999000"
     nested: "SELECT PrimaryKey FROM sqAlbum WHERE Parent = #{id}"

photos:
#  photoKeys is result of albums SQL above
# SqFileImage: photoKey,imageType -> primaryKey
# imageType 6 -> orig , 7 -> arch , 5-> thumb
   thumb: "SELECT primaryKey FROM SqFileImage WHERE imageType = 5 AND photoKey = #{photoKey}"
   image: "SELECT primaryKey FROM SqFileImage WHERE imageType = 6 AND photoKey = #{photoKey}"

# tpl below uses one of the 2 above
   path: "SELECT relativePath FROM SqFileInfo WHERE primaryKey in (#{select})"
   dimensions: "SELECT imageWidth, imageHeight FROM SqFileImage WHERE primaryKey in (#{select})"


   
